(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.AnalyticsEngine = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  const DAY = 86400000;
  const DEFAULT_OPTIONS = { minStrongQuestions: 20, neglectDays: 14, today: null };
  const clone = (v) => JSON.parse(JSON.stringify(v || {}));
  const num = (v) => Number.isFinite(Number(v)) ? Number(v) : 0;
  const pct = (a, b) => b ? Number((a / b * 100).toFixed(1)) : 0;
  const iso = (d) => new Date(d).toISOString().slice(0, 10);
  const parse = (d) => new Date(`${String(d).slice(0, 10)}T00:00:00Z`);
  const daysBetween = (a, b) => Math.max(0, Math.round((parse(b) - parse(a)) / DAY) + 1);
  const addDays = (date, days) => iso(new Date(parse(date).getTime() + days * DAY));
  const inPeriod = (date, period) => date && String(date).slice(0, 10) >= period.start && String(date).slice(0, 10) <= period.end;
  const key = (v) => String(v || "").trim().toLowerCase();
  const done = (v) => ["concluída", "concluido", "concluído", "dominado", "estudado", "revisado"].includes(key(v));
  const ignored = (v) => ["ignorado", "ignorada"].includes(key(v));
  function getAnalyticsPeriod(selection = "30d", custom = {}, options = {}) {
    const today = options.today || iso(new Date());
    if (selection === "custom") {
      const start = custom.start || today, end = custom.end || start;
      return { type: "custom", start: start <= end ? start : end, end: end >= start ? end : start, days: daysBetween(start <= end ? start : end, end >= start ? end : start) };
    }
    const days = selection === "7d" ? 7 : selection === "90d" ? 90 : 30;
    return { type: selection, start: addDays(today, -(days - 1)), end: today, days };
  }
  function previousPeriod(period) { return { type: "previous", start: addDays(period.start, -period.days), end: addDays(period.start, -1), days: period.days }; }
  function normalizeState(state = {}) { return { subjects: state.subjects || [], studies: state.studies || [], questionLogs: state.questionLogs || [], dailyGoals: state.dailyGoals || [], syllabusItems: state.syllabusItems || [], smartReviews: state.smartReviews || [], simulados: state.simulados || [] }; }
  function filterDataByPeriod(state, period) { const s = normalizeState(state); return { ...s, studies: s.studies.filter(x => inPeriod(x.date, period)), questionLogs: s.questionLogs.filter(x => inPeriod(x.date, period)), dailyGoals: s.dailyGoals.filter(x => inPeriod(x.date || x.data, period)), smartReviews: s.smartReviews.filter(x => inPeriod(x.date || x.doneAt || x.updatedAt, period)), simulados: s.simulados.filter(x => inPeriod(x.date, period)) }; }
  function studyDiscipline(study, state) { return study.discipline || state.subjects.find(s => s.id === study.subjectId)?.name || "Sem disciplina"; }
  function calculateStudySummary(state, period) { const f = filterDataByPeriod(state, period), days = new Set(f.studies.filter(s=>num(s.minutes)>0).map(s=>s.date)); const minutes = f.studies.reduce((a,s)=>a+num(s.minutes),0) + f.dailyGoals.reduce((a,g)=>a+num(g.studyActualMinutes ?? g.actualMinutes),0); return { minutes, hours: Number((minutes/60).toFixed(2)), sessions: f.studies.length, studyDays: days.size, dailyAverageHours: Number((minutes/60/Math.max(1, period.days)).toFixed(2)), reviews: f.smartReviews.filter(r=>done(r.status)||r.status==="revisado").length }; }
  function calculateQuestionSummary(state, period) { const f = filterDataByPeriod(state, period); const rows = [...f.studies.map(s=>({total:num(s.questions)||num(s.correct)+num(s.wrong)+num(s.blank), correct:num(s.correct), wrong:num(s.wrong), blank:num(s.blank), discipline:studyDiscipline(s,state), date:s.date, board:s.board})), ...f.questionLogs.map(q=>({total:num(q.total)||num(q.questions)||num(q.correct)+num(q.wrong)+num(q.blank), correct:num(q.correct), wrong:num(q.wrong), blank:num(q.blank), discipline:q.discipline||"Sem disciplina", date:q.date, board:q.board}))]; const ceb = rows.filter(r=>!r.board || /cebraspe|cespe/i.test(r.board)); const sum = rows.reduce((a,r)=>(a.total+=r.total,a.correct+=r.correct,a.wrong+=r.wrong,a.blank+=r.blank,a),{total:0,correct:0,wrong:0,blank:0}); sum.accuracyPct = pct(sum.correct, sum.correct + sum.wrong); sum.cebraspeNet = ceb.reduce((a,r)=>a+r.correct-r.wrong,0); sum.rows = rows; return sum; }
  function calculateGoalStats(state, period) { const goals = filterDataByPeriod(state, period).dailyGoals; const completed = goals.filter(g=>done(g.status)).length; return { planned: goals.length, completed, completionPct: pct(completed, goals.length), pending: goals.length - completed }; }
  function calculateCebraspeStats(state, period) { const q = calculateQuestionSummary(state, period); const byDiscipline = {}; q.rows.filter(r=>!r.board || /cebraspe|cespe/i.test(r.board)).forEach(r=>{ const d=r.discipline||"Sem disciplina"; byDiscipline[d] ||= {discipline:d, net:0, correct:0, wrong:0, blank:0, total:0}; byDiscipline[d].net += r.correct-r.wrong; byDiscipline[d].correct+=r.correct; byDiscipline[d].wrong+=r.wrong; byDiscipline[d].blank+=r.blank; byDiscipline[d].total+=r.total; }); const weekly = {}; q.rows.forEach(r=>{ const w = addDays(r.date, -(parse(r.date).getUTCDay())); weekly[w]=(weekly[w]||0)+r.correct-r.wrong; }); const entries=Object.entries(weekly).map(([week,net])=>({week,net})); return { net: q.cebraspeNet, byDiscipline:Object.values(byDiscipline).sort((a,b)=>b.net-a.net), weeklyEvolution: entries, bestPeriod: entries.sort((a,b)=>b.net-a.net)[0]||null, worstPeriod: entries.sort((a,b)=>a.net-b.net)[0]||null, topAdders:Object.values(byDiscipline).filter(d=>d.net>0).sort((a,b)=>b.net-a.net).slice(0,5), topSubtractors:Object.values(byDiscipline).filter(d=>d.net<0).sort((a,b)=>a.net-b.net).slice(0,5) }; }
  function calculateDisciplinePerformance(state, period, prev = previousPeriod(period), options = {}) { const opt={...DEFAULT_OPTIONS,...options}, s=normalizeState(state), q=calculateQuestionSummary(s, period), qp=calculateQuestionSummary(s, prev), study=filterDataByPeriod(s,period).studies, goals=filterDataByPeriod(s,period).dailyGoals; const map={}; function row(d){ map[d] ||= {discipline:d,hours:0,questions:0,correct:0,wrong:0,blank:0,net:0,goals:0,goalsDone:0,regularity:0,evolution:null,justification:""}; return map[d]; } study.forEach(x=>{ row(studyDiscipline(x,s)).hours += num(x.minutes)/60; }); q.rows.forEach(x=>{ const r=row(x.discipline); r.questions+=x.total; r.correct+=x.correct; r.wrong+=x.wrong; r.blank+=x.blank; r.net+=x.correct-x.wrong; }); goals.forEach(g=>{ const r=row(g.discipline||"Sem disciplina"); r.goals++; if(done(g.status)) r.goalsDone++; }); Object.values(map).forEach(r=>{ const prevRows=qp.rows.filter(x=>key(x.discipline)===key(r.discipline)); const prevAcc=pct(prevRows.reduce((a,x)=>a+x.correct,0), prevRows.reduce((a,x)=>a+x.correct+x.wrong,0)); r.accuracyPct=pct(r.correct,r.correct+r.wrong); r.goalPct=pct(r.goalsDone,r.goals); r.evolution = prevRows.length ? Number((r.accuracyPct-prevAcc).toFixed(1)) : null; r.isStrong = r.questions >= opt.minStrongQuestions && r.accuracyPct >= 70 && r.net > 0 && (r.goalPct >= 60 || !r.goals); r.isCritical = (r.questions >= 5 && (r.accuracyPct < 55 || r.net <= 0 || r.wrong > r.correct)) || (r.goals >= 2 && r.goalPct < 50) || (r.evolution !== null && r.evolution <= -10); r.justification = r.isStrong ? `${r.questions} questões, ${r.accuracyPct}% de acerto e líquido ${r.net}.` : r.isCritical ? `${r.accuracyPct}% de acerto, líquido ${r.net}${r.evolution!==null?` e evolução ${r.evolution} p.p.`:""}.` : r.questions < opt.minStrongQuestions ? `Amostra de ${r.questions} questões abaixo do mínimo de ${opt.minStrongQuestions}.` : "Indicadores intermediários."; r.hours=Number(r.hours.toFixed(2)); }); return Object.values(map).sort((a,b)=>b.questions-a.questions); }
  function calculateSubjectNeglect(state, period, options={}) { const opt={...DEFAULT_OPTIONS,...options}, s=normalizeState(state), today=period.end; return s.syllabusItems.filter(i=>!done(i.status)&&!ignored(i.status)).map(i=>{ const studies=s.studies.filter(x=>(x.syllabusItemId&&x.syllabusItemId===i.id)||key(x.topic)===key(i.subject)); const qs=s.questionLogs.filter(x=>(x.syllabusItemId&&x.syllabusItemId===i.id)||(key(x.subject)===key(i.subject)&&key(x.discipline)===key(i.discipline))); const lastStudy=studies.map(x=>x.date).sort().at(-1)||""; const lastQuestion=qs.map(x=>x.date).sort().at(-1)||""; const pending=s.dailyGoals.filter(g=>(g.syllabusItemId===i.id||(key(g.subject)===key(i.subject)&&key(g.discipline)===key(i.discipline)))&&!done(g.status)).length; const days=lastStudy?daysBetween(lastStudy,today)-1:999; return {discipline:i.discipline||"Sem disciplina", subject:i.subject||i.topic||"Assunto", daysSinceLastStudy:days, lastQuestionDate:lastQuestion||"Sem registro", pendingGoals:pending, reason: !lastStudy?"Sem estudo registrado": days>=opt.neglectDays?`${days} dias sem estudo`: pending?"Metas pendentes":""}; }).filter(x=>x.daysSinceLastStudy>=opt.neglectDays||x.pendingGoals>0||x.lastQuestionDate==="Sem registro"); }
  function calculateStudyEfficiency(state, period) { const study=calculateStudySummary(state,period), q=calculateQuestionSummary(state,period), hours=study.hours; return { warning:"Eficiência é uma medida complementar e não substitui a importância ou dificuldade da disciplina.", questionsPerHour: hours?pct(q.total,hours)/100:null, correctPerHour: hours?pct(q.correct,hours)/100:null, netPerHour: hours?Number((q.cebraspeNet/hours).toFixed(2)):null, averageMinutesPerQuestion:q.total?Number((study.minutes/q.total).toFixed(1)):null }; }
  function calculateMockExamStats(state, period) { const mocks=filterDataByPeriod(state,period).simulados.sort((a,b)=>a.date.localeCompare(b.date)); const nets=mocks.map(m=>num(m.net)); const avg=nets.length?Number((nets.reduce((a,b)=>a+b,0)/nets.length).toFixed(1)):0; return { count:mocks.length, averageNet:avg, bestNet:nets.length?Math.max(...nets):0, worstNet:nets.length?Math.min(...nets):0, trend:nets.length<2?"dados insuficientes":nets.at(-1)>nets[0]?"aumento":nets.at(-1)<nets[0]?"queda":"estabilidade", goalDistance:mocks.at(-1)?num(mocks.at(-1).net)-num(mocks.at(-1).goal):null, byDiscipline:[] }; }
  function compareAnalyticsPeriods(state, period) { const prev=previousPeriod(period), a={study:calculateStudySummary(state,period), q:calculateQuestionSummary(state,period), g:calculateGoalStats(state,period), m:calculateMockExamStats(state,period)}, b={study:calculateStudySummary(state,prev), q:calculateQuestionSummary(state,prev), g:calculateGoalStats(state,prev), m:calculateMockExamStats(state,prev)}; const cmp=(cur,old)=>({current:cur,previous:old,direction: old===0&&cur===0?"ausência de dados suficientes":old===0?"aumento sem percentual-base":Math.abs(cur-old)<0.01?"estabilidade":cur>old?"aumento":"queda", delta:Number((cur-old).toFixed(2)), percentChange:old?Number(((cur-old)/Math.abs(old)*100).toFixed(1)):null}); return { hours:cmp(a.study.hours,b.study.hours), questions:cmp(a.q.total,b.q.total), accuracyPct:cmp(a.q.accuracyPct,b.q.accuracyPct), cebraspeNet:cmp(a.q.cebraspeNet,b.q.cebraspeNet), goalsCompleted:cmp(a.g.completed,b.g.completed), studyDays:cmp(a.study.studyDays,b.study.studyDays), mockAverage:cmp(a.m.averageNet,b.m.averageNet) }; }
  function classifyOverallSituation(summary, evolution, disciplines, dataQuality) { if (dataQuality.insufficient) return { classification:"DADOS INSUFICIENTES", explanation:"Há poucos lançamentos no período para um diagnóstico confiável." }; const critical=disciplines.filter(d=>d.isCritical).length, strong=disciplines.filter(d=>d.isStrong).length; if (summary.questionsTotal>=20 && summary.accuracyPct>=70 && summary.cebraspeNet>0 && critical===0) return {classification:"FAVORÁVEL", explanation:"O período combina volume mínimo, acerto elevado e líquido Cebraspe positivo."}; if (critical>=3 || summary.cebraspeNet<0 || summary.accuracyPct<50) return {classification:"CRÍTICA", explanation:`Desempenho exige atenção: líquido ${summary.cebraspeNet}, ${summary.accuracyPct}% de acerto e ${critical} disciplina(s) crítica(s).`}; return {classification:"ATENÇÃO", explanation:`Há ${strong} disciplina(s) forte(s), mas ${critical} ponto(s) crítico(s) ou lacunas de regularidade.`}; }
  function generateStrategicRecommendations(analysis) { const high=analysis.criticalDisciplines.map(d=>`${d.discipline}: ${d.justification}`).slice(0,5); const subjects=analysis.neglectedSubjects.slice(0,5).map(s=>`${s.discipline} — ${s.subject}: ${s.reason}`); return { highPriority: high, maintenance: analysis.strongDisciplines.slice(0,5).map(d=>`${d.discipline}: manter revisões e questões.`), reduceExcess: analysis.disciplines.filter(d=>d.hours>0 && d.accuracyPct>=75 && d.questions>=20).slice(0,3).map(d=>`${d.discipline}: desempenho estabilizado; evitar concentração excessiva.`), prioritySubjects: subjects, weeklyDistribution: high.length?"Reserve 50% a 60% da semana para críticas/negligenciadas, 25% para manutenção e 15% para revisão geral.":"Distribua a semana entre manutenção, revisão e cobertura de assuntos pendentes.", reviewSuggestions: subjects.length?"Revisar assuntos negligenciados antes de novas frentes.":"Manter revisões espaçadas.", suggestedQuestions: high.length?"Priorize 30 a 50 questões semanais nas disciplinas críticas, ajustando ao tempo disponível.":"Manter lote semanal de questões por disciplina ativa.", imbalanceAlerts: analysis.dataQuality.metricsUnavailable }; }
  function dataQuality(state, period, summary) { const s=normalizeState(state); const disciplines = new Set([...s.subjects.map(x=>x.name), ...s.syllabusItems.map(x=>x.discipline)].filter(Boolean)); const launched = new Set([...filterDataByPeriod(s,period).studies.map(x=>studyDiscipline(x,s)), ...filterDataByPeriod(s,period).questionLogs.map(x=>x.discipline)].filter(Boolean)); return { disciplinesWithoutEntries:[...disciplines].filter(d=>!launched.has(d)), studiesWithoutSubject:s.studies.filter(x=>!x.subjectId&&!x.discipline).length, questionsWithoutDiscipline:s.questionLogs.filter(x=>!x.discipline).length, insufficient: summary.sessions<2 && summary.questionsTotal<10 && summary.mockExams===0, metricsUnavailable:[] }; }
  function buildStrategicAnalysis(state, selection="30d", custom={}, options={}) { const before=JSON.stringify(state); const period=getAnalyticsPeriod(selection,custom,options), previous=previousPeriod(period); const study=calculateStudySummary(state,period), questions=calculateQuestionSummary(state,period), goals=calculateGoalStats(state,period), mockExams=calculateMockExamStats(state,period); const summary={...study, questionsTotal:questions.total, correct:questions.correct, wrong:questions.wrong, blank:questions.blank, accuracyPct:questions.accuracyPct, cebraspeNet:questions.cebraspeNet, goalsPlanned:goals.planned, goalsCompleted:goals.completed, goalCompletionPct:goals.completionPct, mockExams:mockExams.count}; const disciplines=calculateDisciplinePerformance(state,period,previous,options); const dq=dataQuality(state,period,summary); const analysis={ period, previousPeriod:previous, overallSituation:null, summary, evolution:compareAnalyticsPeriods(state,period), disciplines, strongDisciplines:disciplines.filter(d=>d.isStrong), criticalDisciplines:disciplines.filter(d=>d.isCritical), neglectedSubjects:calculateSubjectNeglect(state,period,options), efficiency:calculateStudyEfficiency(state,period), cebraspe:calculateCebraspeStats(state,period), mockExams, recommendations:null, dataQuality:dq }; analysis.overallSituation=classifyOverallSituation(summary,analysis.evolution,disciplines,dq); analysis.recommendations=generateStrategicRecommendations(analysis); analysis.stateUnchanged = before === JSON.stringify(state); return analysis; }
  return { getAnalyticsPeriod, filterDataByPeriod, calculateStudySummary, calculateQuestionSummary, calculateCebraspeStats, calculateGoalStats, calculateDisciplinePerformance, calculateSubjectNeglect, calculateStudyEfficiency, calculateMockExamStats, compareAnalyticsPeriods, classifyOverallSituation, generateStrategicRecommendations, buildStrategicAnalysis };
});
