(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.AnalyticsEngine = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  const DAY = 86400000;
  const DEFAULT_OPTIONS = { minStrongQuestions: 20, preliminaryQuestions: 20, confirmedQuestions: 50, neglectDays: 14, today: null };
  const clone = (v) => JSON.parse(JSON.stringify(v || {}));
  const num = (v) => Number.isFinite(Number(v)) ? Number(v) : 0;
  const pct = (a, b) => b ? Number((a / b * 100).toFixed(1)) : 0;
  const iso = (d) => new Date(d).toISOString().slice(0, 10);
  const parse = (d) => new Date(`${String(d).slice(0, 10)}T00:00:00Z`);
  const daysBetween = (a, b) => Math.max(0, Math.round((parse(b) - parse(a)) / DAY) + 1);
  const addDays = (date, days) => iso(new Date(parse(date).getTime() + days * DAY));
  const inPeriod = (date, period) => date && String(date).slice(0, 10) >= period.start && String(date).slice(0, 10) <= period.end;
  const key = (v) => String(v || "").trim().toLowerCase();
  const done = (v) => ["concluída", "concluido", "concluído", "dominado", "estudado", "revisado"].includes(key(v));
  const ignored = (v) => ["ignorado", "ignorada"].includes(key(v));
  function getAnalyticsPeriod(selection = "30d", custom = {}, options = {}) {
    const today = options.today || iso(new Date());
    if (selection === "custom") {
      const start = custom.start || today, end = custom.end || start;
      return { type: "custom", start: start <= end ? start : end, end: end >= start ? end : start, days: daysBetween(start <= end ? start : end, end >= start ? end : start) };
    }
    const days = selection === "7d" ? 7 : selection === "90d" ? 90 : 30;
    return { type: selection, start: addDays(today, -(days - 1)), end: today, days };
  }
  function previousPeriod(period) { return { type: "previous", start: addDays(period.start, -period.days), end: addDays(period.start, -1), days: period.days }; }
  function normalizeState(state = {}) { return { subjects: state.subjects || [], studies: state.studies || [], questionLogs: state.questionLogs || [], dailyGoals: state.dailyGoals || [], syllabusItems: state.syllabusItems || [], smartReviews: state.smartReviews || [], simulados: state.simulados || [] }; }
  function filterDataByPeriod(state, period) { const s = normalizeState(state); return { ...s, studies: s.studies.filter(x => inPeriod(x.date, period)), questionLogs: s.questionLogs.filter(x => inPeriod(x.date, period)), dailyGoals: s.dailyGoals.filter(x => inPeriod(x.date || x.data, period)), smartReviews: s.smartReviews.filter(x => inPeriod(x.date || x.doneAt || x.updatedAt, period)), simulados: s.simulados.filter(x => inPeriod(x.date, period)) }; }
  function studyDiscipline(study, state) { return study.discipline || state.subjects.find(s => s.id === study.subjectId)?.name || "Sem disciplina"; }
  function calculateStudySummary(state, period) { const f = filterDataByPeriod(state, period), days = new Set(f.studies.filter(s=>num(s.minutes)>0).map(s=>s.date)); const minutes = f.studies.reduce((a,s)=>a+num(s.minutes),0) + f.dailyGoals.reduce((a,g)=>a+num(g.studyActualMinutes ?? g.actualMinutes),0); return { minutes, hours: Number((minutes/60).toFixed(2)), sessions: f.studies.length, studyDays: days.size, dailyAverageHours: Number((minutes/60/Math.max(1, period.days)).toFixed(2)), reviews: f.smartReviews.filter(r=>done(r.status)||r.status==="revisado").length }; }
  function firstValid(obj, names) { for (const n of names) if (obj && Object.prototype.hasOwnProperty.call(obj,n) && Number.isFinite(Number(obj[n]))) return Number(obj[n]); return null; }
  function firstText(obj, names) { for (const n of names) if (obj && obj[n] !== undefined && obj[n] !== null && String(obj[n]).trim()) return String(obj[n]).trim(); return ""; }
  function mockRowsArray(m) { return [m?.disciplineResults, m?.disciplines, m?.resultadosPorDisciplina].find(Array.isArray) || []; }
  function hasMockQuestionDetails(obj) { return firstValid(obj,["correct","acertos"]) !== null || firstValid(obj,["wrong","erros"]) !== null || firstValid(obj,["blank","brancos"]) !== null || firstValid(obj,["total","totalQuestions","questoes"]) !== null; }
  function buildMockQuestionRow(m, source, discipline, detailed) { const correct=firstValid(source,["correct","acertos"]), wrong=firstValid(source,["wrong","erros"]), blank=firstValid(source,["blank","brancos"]), rawTotal=firstValid(source,["total","totalQuestions","questoes"]); const c=correct??0,w=wrong??0,b=blank??0, parts=c+w+b; const quality=[]; let total=rawTotal; if(total===null && parts>0){ total=parts; quality.push("simulado sem total; total calculado por acertos + erros + brancos"); } if(rawTotal!==null && parts>0 && rawTotal!==parts) quality.push("total incompatível com acertos, erros e brancos"); if(!firstText(m,["board","banca"])) quality.push("simulado sem banca"); const sufficient=total!==null && total>0; if(!sufficient) quality.push(hasMockQuestionDetails(source)?"simulado sem total":"simulado apenas com nota líquida ou sem detalhamento suficiente"); if(!detailed) quality.push("simulado sem detalhamento por disciplina"); return { source:"simulado", sourceId:m.id||m.sourceId||m.mockExamId||"", mockExamId:m.mockExamId||m.id||"", date:firstText(m,["date","data","createdAt"]), title:firstText(m,["title","name","nome"])||"Simulado", discipline:discipline||"Simulado — sem detalhamento por disciplina", total:sufficient?total:0, correct:sufficient?c:0, wrong:sufficient?w:0, blank:sufficient?b:0, board:firstText(source,["board","banca"])||firstText(m,["board","banca"]), detailed:!!detailed, dataQuality:quality }; }
  function normalizeMockExamQuestionRows(state = {}, period) { const s=normalizeState(state); return s.simulados.filter(m=>!period||inPeriod(firstText(m,["date","data","createdAt"]),period)).flatMap(m=>{ const details=mockRowsArray(m).filter(hasMockQuestionDetails); if(details.length) return details.map(d=>buildMockQuestionRow(m,d,firstText(d,["discipline","disciplina","name","nome"]),true)); return [buildMockQuestionRow(m,m,"Simulado — sem detalhamento por disciplina",false)]; }); }
  function isDuplicateQuestionSource(mockRow, rows = []) { const ids=[mockRow.sourceId,mockRow.mockExamId].filter(Boolean).map(String); if(mockRow.alreadyInQuestionBank) return true; return rows.some(r=>[r.sourceId,r.mockExamId,r.linkedSimuladoId,r.originId,r.questionLogId].filter(Boolean).map(String).some(id=>ids.includes(id))); }
  function sourceSum(rows) { const sum=rows.reduce((a,r)=>(a.total+=num(r.total),a.correct+=num(r.correct),a.wrong+=num(r.wrong),a.blank+=num(r.blank),a),{total:0,correct:0,wrong:0,blank:0}); sum.accuracyPct=pct(sum.correct,sum.correct+sum.wrong); sum.cebraspeNet=rows.filter(r=>!r.board||/cebraspe|cespe/i.test(r.board)).reduce((a,r)=>a+num(r.correct)-num(r.wrong),0); return sum; }
  function calculateQuestionSummary(state, period) { const f = filterDataByPeriod(state, period); const studyRows = f.studies.map(s=>({source:"studySession",sourceId:s.id||"",total:num(s.questions)||num(s.correct)+num(s.wrong)+num(s.blank), correct:num(s.correct), wrong:num(s.wrong), blank:num(s.blank), discipline:studyDiscipline(s,state), date:s.date, board:s.board, linkedSimuladoId:s.linkedSimuladoId, originId:s.originId})); const logRows = f.questionLogs.map(q=>({source:"questionLog",sourceId:q.id||"",questionLogId:q.id||"",total:num(q.total)||num(q.questions)||num(q.correct)+num(q.wrong)+num(q.blank), correct:num(q.correct), wrong:num(q.wrong), blank:num(q.blank), discipline:q.discipline||"Sem disciplina", date:q.date, board:q.board, linkedSimuladoId:q.linkedSimuladoId, mockExamId:q.mockExamId, originId:q.originId})); const mockAll=normalizeMockExamQuestionRows(state,period); const nonMock=[...studyRows,...logRows]; const excludedMockExams=[]; const mockRows=mockAll.filter(r=>{ const m=f.simulados.find(x=>String(x.id||x.mockExamId||"")===String(r.mockExamId||r.sourceId||""))||{}; const marked=!!(m.alreadyInQuestionBank||m.questionsAlreadyInBank||m.jaLancadoBancoQuestoes); if(marked||isDuplicateQuestionSource(r,nonMock)){ excludedMockExams.push({...r, reason: marked?"simulado marcado como já lançado no Banco de Questões":"possível duplicidade explicitamente vinculada"}); return false; } return r.total>0; }); const rows=[...nonMock,...mockRows]; const sum=sourceSum(rows); return {...sum, bySource:{studySessions:sourceSum(studyRows), questionLogs:sourceSum(logRows), mockExams:sourceSum(mockRows)}, consolidatedRows:rows, excludedMockExams, dataQuality:[...mockAll.flatMap(r=>r.dataQuality||[]),...excludedMockExams.map(x=>x.reason)], rows}; }
  function calculateGoalStats(state, period) { const goals = filterDataByPeriod(state, period).dailyGoals; const completed = goals.filter(g=>done(g.status)).length; return { planned: goals.length, completed, completionPct: pct(completed, goals.length), pending: goals.length - completed }; }
  function calculateCebraspeStats(state, period) { const q = calculateQuestionSummary(state, period); const byDiscipline = {}; q.rows.filter(r=>!r.board || /cebraspe|cespe/i.test(r.board)).forEach(r=>{ const d=r.discipline||"Sem disciplina"; byDiscipline[d] ||= {discipline:d, net:0, correct:0, wrong:0, blank:0, total:0}; byDiscipline[d].net += r.correct-r.wrong; byDiscipline[d].correct+=r.correct; byDiscipline[d].wrong+=r.wrong; byDiscipline[d].blank+=r.blank; byDiscipline[d].total+=r.total; }); const weekly = {}; q.rows.forEach(r=>{ const w = addDays(r.date, -(parse(r.date).getUTCDay())); weekly[w]=(weekly[w]||0)+r.correct-r.wrong; }); const entries=Object.entries(weekly).map(([week,net])=>({week,net})); return { net: q.cebraspeNet, byDiscipline:Object.values(byDiscipline).sort((a,b)=>b.net-a.net), weeklyEvolution: entries, bestPeriod: entries.sort((a,b)=>b.net-a.net)[0]||null, worstPeriod: entries.sort((a,b)=>a.net-b.net)[0]||null, topAdders:Object.values(byDiscipline).filter(d=>d.net>0).sort((a,b)=>b.net-a.net).slice(0,5), topSubtractors:Object.values(byDiscipline).filter(d=>d.net<0).sort((a,b)=>a.net-b.net).slice(0,5) }; }
  function calculateDisciplinePerformance(state, period, prev = previousPeriod(period), options = {}) { const opt={...DEFAULT_OPTIONS,...options}, s=normalizeState(state), q=calculateQuestionSummary(s, period), qp=calculateQuestionSummary(s, prev), study=filterDataByPeriod(s,period).studies, goals=filterDataByPeriod(s,period).dailyGoals; const map={}; function row(d){ map[d] ||= {discipline:d,hours:0,questions:0,correct:0,wrong:0,blank:0,net:0,goals:0,goalsDone:0,regularity:0,evolution:null,justification:""}; return map[d]; } study.forEach(x=>{ row(studyDiscipline(x,s)).hours += num(x.minutes)/60; }); q.rows.filter(x=>!(x.source==="simulado" && !x.detailed)).forEach(x=>{ const r=row(x.discipline); r.questions+=x.total; r.correct+=x.correct; r.wrong+=x.wrong; r.blank+=x.blank; r.net+=x.correct-x.wrong; }); goals.forEach(g=>{ const r=row(g.discipline||"Sem disciplina"); r.goals++; if(done(g.status)) r.goalsDone++; }); Object.values(map).forEach(r=>{ const prevRows=qp.rows.filter(x=>key(x.discipline)===key(r.discipline)); const prevAcc=pct(prevRows.reduce((a,x)=>a+x.correct,0), prevRows.reduce((a,x)=>a+x.correct+x.wrong,0)); r.accuracyPct=pct(r.correct,r.correct+r.wrong); r.goalPct=pct(r.goalsDone,r.goals); const prevTotal=prevRows.reduce((a,x)=>a+x.total,0); r.evolution = (prevRows.length && prevTotal>=20 && r.questions>=20) ? Number((r.accuracyPct-prevAcc).toFixed(1)) : null; r.isStrong = r.questions >= opt.minStrongQuestions && r.accuracyPct >= 70 && r.net > 0 && (r.goalPct >= 60 || !r.goals); r.isCritical = (r.questions >= 5 && (r.accuracyPct < 55 || r.net <= 0 || r.wrong > r.correct)) || (r.goals >= 2 && r.goalPct < 50) || (r.evolution !== null && r.evolution <= -10); r.justification = r.isStrong ? `${r.questions} questões, ${r.accuracyPct}% de acerto e líquido ${r.net}.` : r.isCritical ? `${r.accuracyPct}% de acerto, líquido ${r.net}${r.evolution!==null?` e evolução ${r.evolution} p.p.`:""}.` : r.questions < opt.minStrongQuestions ? `Amostra de ${r.questions} questões abaixo do mínimo de ${opt.minStrongQuestions}.` : "Indicadores intermediários."; r.hours=Number(r.hours.toFixed(2)); }); return Object.values(map).sort((a,b)=>b.questions-a.questions); }
  function calculateSubjectNeglect(state, period, options={}) { const opt={...DEFAULT_OPTIONS,...options}, s=normalizeState(state), today=period.end; return s.syllabusItems.filter(i=>!done(i.status)&&!ignored(i.status)).map(i=>{ const studies=s.studies.filter(x=>(x.syllabusItemId&&x.syllabusItemId===i.id)||key(x.topic)===key(i.subject)); const qs=s.questionLogs.filter(x=>(x.syllabusItemId&&x.syllabusItemId===i.id)||(key(x.subject)===key(i.subject)&&key(x.discipline)===key(i.discipline))); const lastStudy=studies.map(x=>x.date).sort().at(-1)||""; const lastQuestion=qs.map(x=>x.date).sort().at(-1)||""; const pending=s.dailyGoals.filter(g=>(g.syllabusItemId===i.id||(key(g.subject)===key(i.subject)&&key(g.discipline)===key(i.discipline)))&&!done(g.status)).length; const days=lastStudy?daysBetween(lastStudy,today)-1:999; return {discipline:i.discipline||"Sem disciplina", subject:i.subject||i.topic||"Assunto", daysSinceLastStudy:days, lastQuestionDate:lastQuestion||"Sem registro", pendingGoals:pending, fact:!lastStudy?"Não há estudo registrado para este assunto.":`Último estudo registrado em ${lastStudy}.`, inference:(!lastStudy||pending||days>=opt.neglectDays)?"Isso pode indicar negligência.":"", reason: !lastStudy?"Fato: Não há estudo registrado para este assunto. Inferência: Isso pode indicar negligência.": days>=opt.neglectDays?`Fato: ${days} dias sem estudo. Inferência: Isso pode indicar negligência.`: pending?"Fato: há meta pendente. Inferência: Isso pode indicar negligência.":""}; }).filter(x=>x.daysSinceLastStudy>=opt.neglectDays||x.pendingGoals>0||x.lastQuestionDate==="Sem registro"); }
  function calculateStudyEfficiency(state, period) { const study=calculateStudySummary(state,period), q=calculateQuestionSummary(state,period), hours=study.hours; return { warning:"Eficiência é uma medida complementar e não substitui a importância ou dificuldade da disciplina.", questionsPerHour: hours?pct(q.total,hours)/100:null, correctPerHour: hours?pct(q.correct,hours)/100:null, netPerHour: hours?Number((q.cebraspeNet/hours).toFixed(2)):null, averageMinutesPerQuestion:q.total?Number((study.minutes/q.total).toFixed(1)):null }; }
  function calculateMockExamStats(state, period) { const mocks=filterDataByPeriod(state,period).simulados.sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))); const nets=mocks.map(m=>num(m.net ?? m.score ?? m.result)).filter(Number.isFinite); const avg=nets.length?Number((nets.reduce((a,b)=>a+b,0)/nets.length).toFixed(1)):0; return { count:mocks.length, averageNet:avg, bestNet:nets.length?Math.max(...nets):0, worstNet:nets.length?Math.min(...nets):0, trend:nets.length<2?"dados insuficientes":nets.at(-1)>nets[0]?"aumento":nets.at(-1)<nets[0]?"queda":"estabilidade", goalDistance:mocks.at(-1)?num(mocks.at(-1).net)-num(mocks.at(-1).goal):null, byDiscipline:[] }; }
  function calculateDisciplineSampleConfidence(questions) { const q=num(questions); if(q<20) return { sampleConfidence:"low", sampleLabel:"CONFIANÇA BAIXA", classificationStatus:"insufficient" }; if(q<50) return { sampleConfidence:"medium", sampleLabel:"CONFIANÇA MÉDIA", classificationStatus:"preliminary" }; return { sampleConfidence:"high", sampleLabel:"CONFIANÇA ALTA", classificationStatus:"confirmed" }; }
  function validDate(v){ const d=String(v||'').slice(0,10); return /^\d{4}-\d{2}-\d{2}$/.test(d) && !Number.isNaN(parse(d).getTime()) ? d : ""; }
  function calculateBaseline(state={}) { const s=normalizeState(state); const dates=[]; s.studies.forEach(x=>dates.push(validDate(x.date))); s.questionLogs.forEach(x=>dates.push(validDate(x.date))); s.dailyGoals.forEach(x=>dates.push(validDate(x.date||x.data||x.createdAt))); s.smartReviews.forEach(x=>dates.push(validDate(x.date||x.doneAt||x.updatedAt||x.createdAt))); s.simulados.forEach(x=>dates.push(validDate(x.date||x.createdAt))); const firstRecordDate=dates.filter(Boolean).sort()[0]||""; if(!firstRecordDate) return { firstRecordDate:"", daysSinceFirstRecord:0, checkpoint7Days:"", checkpoint14Days:"", checkpoint30Days:"" }; const today=iso(new Date()); return { firstRecordDate, daysSinceFirstRecord:daysBetween(firstRecordDate,today), checkpoint7Days:addDays(firstRecordDate,6), checkpoint14Days:addDays(firstRecordDate,13), checkpoint30Days:addDays(firstRecordDate,29) }; }
  function plural(n,s,p){return `${n} ${n===1?s:p}`;}
  function calculateNextDataMilestones(state, period, analysis, components) { const milestones=[]; const q=components.questions.value; if(q<100) milestones.push(`Registrar mais ${plural(100-q,"questão","questões")} para atingir 100.`); else if(q<200) milestones.push(`Registrar mais ${plural(200-q,"questão","questões")} para atingir 200.`); const d=components.activeDays.value; if(d<10) milestones.push(`Completar mais ${plural(10-d,"dia ativo","dias ativos")} de estudo.`); const ses=components.sessions.value; if(ses<12) milestones.push(`Registrar mais ${plural(12-ses,"sessão de estudo","sessões de estudo")}.`); const low=(analysis?.disciplines||[]).filter(x=>x.questions>0&&x.questions<20).sort((a,b)=>b.questions-a.questions)[0]; if(low) milestones.push(`Alcançar 20 questões em ${low.discipline}.`); if(components.mockExams.value<1) milestones.push("Registrar o primeiro simulado quando possível."); return milestones.slice(0,5); }
  function calculateDataMaturity(state={}, period, analysis={}) { const s=normalizeState(state); const filtered=period?filterDataByPeriod(s,period):s; const q=analysis.summary?.questionsTotal ?? calculateQuestionSummary(s,period||getAnalyticsPeriod()).total; const active=(analysis.summary?.studyDays ?? calculateStudySummary(s,period||getAnalyticsPeriod()).studyDays); const sessions=(analysis.summary?.sessions ?? calculateStudySummary(s,period||getAnalyticsPeriod()).sessions); const disc=(analysis.disciplines||[]); const relevantExisting=Math.max(1, Math.min(4, disc.filter(d=>d.questions>0).length)); const covered=disc.filter(d=>d.questions>=20).length; const mocks=analysis.summary?.mockExams ?? filtered.simulados.length; const components={ questions:{value:q,target:200,points:Number((Math.min(q/200,1)*35).toFixed(2))}, activeDays:{value:active,target:10,points:Number((Math.min(active/10,1)*25).toFixed(2))}, sessions:{value:sessions,target:12,points:Number((Math.min(sessions/12,1)*20).toFixed(2))}, disciplineCoverage:{value:covered,target:relevantExisting,points:Number((Math.min(covered/relevantExisting,1)*10).toFixed(2))}, mockExams:{value:mocks,target:2,points:Number((Math.min(mocks/2,1)*10).toFixed(2))} }; const score=Math.max(0,Math.min(100,Math.round(Object.values(components).reduce((a,c)=>a+c.points,0)))); const level=score<35?"low":score<70?"medium":"high"; const phase=score<35?"calibration":score<70?"developing":"reliable"; const label=phase==="calibration"?"FASE DE CALIBRAÇÃO":phase==="developing"?"BASE EM DESENVOLVIMENTO":"ANÁLISE CONSISTENTE"; const explanation=phase==="calibration"?"A base ainda está em formação; os números são reais, mas funcionam como sinais iniciais.":phase==="developing"?"A base já permite identificar sinais iniciais, mas ainda não sustenta conclusões definitivas sobre todas as disciplinas.":"A amostra atual permite uma leitura estratégica mais consistente, mantendo revisão contínua dos dados."; const baseline=calculateBaseline(s); const missingData=[]; if(q<200) missingData.push("mais questões registradas"); if(active<10) missingData.push("mais dias ativos"); if(sessions<12) missingData.push("mais sessões de estudo"); if(covered<relevantExisting) missingData.push("disciplinas com pelo menos 20 questões"); if(mocks<2) missingData.push("simulados para calibrar desempenho"); const out={score,level,phase,label,explanation,components,missingData,nextMilestones:[],baseline}; out.nextMilestones=calculateNextDataMilestones(s,period,analysis,components); return out; }
  function applyConfidenceToAnalysis(analysis) { const maturity=analysis.dataMaturity; analysis.disciplines=(analysis.disciplines||[]).map(d=>({...d,...calculateDisciplineSampleConfidence(d.questions)})); analysis.strongDisciplines=analysis.disciplines.filter(d=>d.classificationStatus==="confirmed"&&d.isStrong); analysis.criticalDisciplines=analysis.disciplines.filter(d=>d.classificationStatus==="confirmed"&&d.isCritical); analysis.preliminarySignals=analysis.disciplines.filter(d=>d.questions>0&&d.classificationStatus!=="confirmed").map(d=>({discipline:d.discipline,questions:d.questions,accuracyPct:d.accuracyPct,net:d.net,sampleLabel:d.sampleLabel,message:`Sinal inicial: ${d.discipline} teve ${d.accuracyPct}% de acerto, mas a amostra contém apenas ${d.questions} questões.`})); if(maturity.phase==="calibration" && !analysis.dataQuality?.insufficient) analysis.overallSituation={classification:"BASE INICIAL EM FORMAÇÃO", explanation:"Os números abaixo são reais, mas a amostra ainda é pequena para uma avaliação estratégica definitiva."}; else if(maturity.phase==="developing") analysis.overallSituation={classification:"SINAIS INICIAIS", explanation:"Há sinais iniciais e possíveis tendências, com amostra ainda em desenvolvimento."}; return analysis; }
  function compareAnalyticsPeriods(state, period) { const prev=previousPeriod(period), a={study:calculateStudySummary(state,period), q:calculateQuestionSummary(state,period), g:calculateGoalStats(state,period), m:calculateMockExamStats(state,period)}, b={study:calculateStudySummary(state,prev), q:calculateQuestionSummary(state,prev), g:calculateGoalStats(state,prev), m:calculateMockExamStats(state,prev)}; const cmp=(cur,old)=>({current:cur,previous:old,direction: old===0&&cur===0?"ausência de dados suficientes":old===0?"dados insuficientes para tendência confiável":Math.abs(cur-old)<0.01?"estabilidade":cur>old?"aumento":"queda", delta:Number((cur-old).toFixed(2)), percentChange:old?Number(((cur-old)/Math.abs(old)*100).toFixed(1)):null}); return { hours:cmp(a.study.hours,b.study.hours), questions:cmp(a.q.total,b.q.total), accuracyPct:cmp(a.q.accuracyPct,b.q.accuracyPct), cebraspeNet:cmp(a.q.cebraspeNet,b.q.cebraspeNet), goalsCompleted:cmp(a.g.completed,b.g.completed), studyDays:cmp(a.study.studyDays,b.study.studyDays), mockAverage:cmp(a.m.averageNet,b.m.averageNet) }; }

  function resolveDashboardPeriod(selection="30d", custom={}, options={}) {
    const today = options.today || iso(new Date());
    if (selection === "all") {
      const st=normalizeState(options.state||{}), dates=[];
      [...st.studies,...st.questionLogs,...st.dailyGoals,...st.smartReviews,...st.simulados].forEach(x=>{ const d=validDate(x.date||x.data||x.doneAt||x.updatedAt||x.createdAt); if(d) dates.push(d); });
      const start=dates.sort()[0]||today; return { type:"all", start, end:today, days:daysBetween(start,today) };
    }
    if (selection === "month") return { type:"month", start: today.slice(0,8)+"01", end: today, days: daysBetween(today.slice(0,8)+"01", today) };
    return getAnalyticsPeriod(selection, custom, options);
  }
  function dashboardPeriod(selection="30d", custom={}, options={}) { return selection && selection.start && selection.end ? selection : resolveDashboardPeriod(selection, custom, options); }
  function matchesFilters(row, filters={}) { const d=key(filters.discipline||"all"), o=key(filters.origin||"consolidated"); const rd=key(row.discipline||row.disciplina||""); const ro=key(row.source||row.origin||""); return (!d||d==="all"||rd===d) && (!o||o==="consolidated"||o==="consolidado"||ro===o||((o==="estudos"||o==="studies")&&ro==="studysession")||((o==="questões"||o==="questoes"||o==="questions")&&ro==="questionlog")||((o==="simulados"||o==="mocks")&&ro==="simulado")); }
  function filteredQuestionRows(state, period, filters={}) { return calculateQuestionSummary(state, period).rows.filter(r=>matchesFilters(r,filters)); }
  function filteredStudies(state, period, filters={}) { const s=normalizeState(state), f=filterDataByPeriod(s,period); return f.studies.map(x=>({...x, discipline:studyDiscipline(x,s), source:"studies"})).filter(r=>matchesFilters(r,filters) && ["consolidated","consolidado","estudos","studies",""].includes(key(filters.origin||"consolidated"))); }
  function summarizeRows(rows){ const out=sourceSum(rows); return {...out, answered:out.correct+out.wrong, accuracyPct:pct(out.correct,out.correct+out.wrong), cebraspeNet:out.correct-out.wrong, sufficientSample:out.correct+out.wrong>=20}; }
  function buildPerformanceSummary(state, period, filters={}) { const studies=filteredStudies(state,period,filters), qrows=filteredQuestionRows(state,period,filters), q=summarizeRows(qrows), f=filterDataByPeriod(state,period); const days=new Set(studies.filter(x=>num(x.minutes)>0).map(x=>validDate(x.date))).size; const minutes=studies.reduce((a,x)=>a+num(x.minutes),0); const goals=f.dailyGoals.filter(g=>matchesFilters({discipline:g.discipline,source:"goals"},{discipline:filters.discipline,origin:"consolidated"})); const mocks=(key(filters.origin||"consolidated")==="consolidated"||key(filters.origin)==="consolidado"||key(filters.origin)==="simulados")?f.simulados.length:0; const activeWeeks=Math.max(1,Math.ceil(period.days/7)); return { minutes, timeLabel:`${Math.floor(minutes/60)}h ${minutes%60}min`, sessions:studies.length, activeDays:days, questions:q.total, correct:q.correct, wrong:q.wrong, blank:q.blank, answered:q.answered, accuracyPct:q.accuracyPct, accuracyLabel:q.sufficientSample?`${q.accuracyPct}%`:"Amostra em desenvolvimento", cebraspeNet:q.cebraspeNet, mockExams:mocks, goalsCompleted:goals.filter(g=>done(g.status)).length, goalsPlanned:goals.length, weeklyRegularityPct:pct(days,Math.min(period.days,activeWeeks*7)), sufficientSample:q.sufficientSample, sampleMessage:q.sufficientSample?"Amostra suficiente para leitura inicial.":"Amostra em desenvolvimento" }; }
  function buildDailyPerformanceSeries(state, period, filters={}) { const out=[]; for(let d=period.start; d<=period.end; d=addDays(d,1)) out.push({date:d, minutes:0, questions:0}); const by=Object.fromEntries(out.map(x=>[x.date,x])); filteredStudies(state,period,filters).forEach(s=>{ const d=validDate(s.date); if(by[d]) by[d].minutes+=num(s.minutes); }); filteredQuestionRows(state,period,filters).forEach(r=>{ const d=validDate(r.date); if(by[d]) by[d].questions+=num(r.total); }); return out; }
  function buildDisciplinePerformanceSeries(state, period, filters={}) { const rows={}; const get=d=>rows[d]||(rows[d]={discipline:d,minutes:0,hours:0,questions:0,correct:0,wrong:0,blank:0,accuracyPct:0,net:0,sampleSize:0}); filteredStudies(state,period,filters).forEach(s=>get(s.discipline||"Sem disciplina").minutes+=num(s.minutes)); filteredQuestionRows(state,period,filters).forEach(q=>{ const r=get(q.discipline||"Sem disciplina"); r.questions+=num(q.total); r.correct+=num(q.correct); r.wrong+=num(q.wrong); r.blank+=num(q.blank); r.net+=num(q.correct)-num(q.wrong); }); return Object.values(rows).map(r=>({...r,hours:Number((r.minutes/60).toFixed(2)),accuracyPct:pct(r.correct,r.correct+r.wrong),sampleSize:r.correct+r.wrong,...calculateDisciplineSampleConfidence(r.correct+r.wrong)})); }
  function buildMockExamEvolutionSeries(state, period) { return filterDataByPeriod(state,period).simulados.slice().sort((a,b)=>String(a.date||a.data||'').localeCompare(String(b.date||b.data||''))).map(m=>{ const rows=normalizeMockExamQuestionRows({simulados:[m]},period); const sum=summarizeRows(rows.filter(r=>r.total>0)); return {date:firstText(m,["date","data","createdAt"]), name:firstText(m,["name","nome","title"])||"Simulado", correct:sum.correct, wrong:sum.wrong, blank:sum.blank, net:sum.correct-sum.wrong || num(m.net??m.score??m.result), accuracyPct:sum.answered?pct(sum.correct,sum.answered):0, details:rows.filter(r=>r.detailed)}; }); }
  function buildPlannedVsActualSeries(state, period, filters={}) { const days=period.days>45?[]:buildDailyPerformanceSeries(state,period,filters).map(x=>({date:x.date, bucket:x.date, actualMinutes:x.minutes, plannedMinutes:0, plannedGoals:0, completedGoals:0})); const map=Object.fromEntries(days.map(x=>[x.date,x])); filterDataByPeriod(state,period).dailyGoals.forEach(g=>{ const d=validDate(g.date||g.data); if(map[d] && matchesFilters({discipline:g.discipline,source:"goals"},{discipline:filters.discipline,origin:"consolidated"})){ map[d].plannedMinutes+=num(g.minutes||g.plannedMinutes); map[d].plannedGoals++; if(done(g.status)) map[d].completedGoals++; }}); return days; }
  function comparePerformancePeriods(current, previous) { const cmp=(cur,prev)=>({current:cur,previous:prev,delta:Number((cur-prev).toFixed(2)),percentChange:prev?Number(((cur-prev)/Math.abs(prev)*100).toFixed(1)):null,trend:prev===0&&cur===0?"estável":prev===0?"sem base anterior para comparação":cur>prev?"aumentou":cur<prev?"diminuiu":"permaneceu estável"}); return {minutes:cmp(current.minutes,previous.minutes),sessions:cmp(current.sessions,previous.sessions),activeDays:cmp(current.activeDays,previous.activeDays),questions:cmp(current.questions,previous.questions),accuracyPct:cmp(current.accuracyPct,previous.accuracyPct),cebraspeNet:cmp(current.cebraspeNet,previous.cebraspeNet),goalsCompleted:cmp(current.goalsCompleted,previous.goalsCompleted)}; }
  function buildDeterministicPerformanceInsights(summary, comparison, maturity, disciplines=[], planned=[]) { const out=[]; if(!summary.questions&&!summary.minutes) out.push("Não há dados suficientes para comparar este período."); if(comparison?.minutes && comparison.minutes.percentChange!==null) out.push(`Você estudou ${Math.abs(comparison.minutes.percentChange)}% ${comparison.minutes.delta>=0?"mais":"menos"} tempo que no período anterior.`); if(comparison?.questions&&comparison?.accuracyPct&&comparison.questions.delta>0&&comparison.accuracyPct.delta<0) out.push("A quantidade de questões aumentou, mas o percentual de acerto caiu."); const top=disciplines.filter(d=>d.minutes>0).sort((a,b)=>b.minutes-a.minutes)[0]; if(top) out.push(`${top.discipline} concentrou o maior tempo de estudo.`); const low=disciplines.find(d=>d.sampleSize>0&&d.classificationStatus==="insufficient"); if(low) out.push(`${low.discipline} possui resultado inicial, mas a amostra ainda é insuficiente.`); const p=planned.reduce((a,x)=>(a.planned+=x.plannedMinutes,a.actual+=x.actualMinutes,a),{planned:0,actual:0}); if(p.planned||p.actual) out.push(`Foram planejados ${p.planned} minutos e realizados ${p.actual} minutos.`); if(maturity?.phase==="calibration") out.push("A leitura está em fase de calibração e deve ser usada como sinal inicial."); return [...new Set(out)].slice(0,6); }
  function buildPerformanceDashboard(state, selection="30d", filters={}, options={}) { const before=JSON.stringify(state); const period=dashboardPeriod(selection, filters.custom||{}, {...options,state}); const summary=buildPerformanceSummary(state,period,filters); const previous=["7d","30d","90d"].includes(period.type)?previousPeriod(period):null; const comparison=previous?comparePerformancePeriods(summary,buildPerformanceSummary(state,previous,filters)):null; const daily=buildDailyPerformanceSeries(state,period,filters), disciplines=buildDisciplinePerformanceSeries(state,period,filters), mocks=buildMockExamEvolutionSeries(state,period), plannedVsActual=buildPlannedVsActualSeries(state,period,filters); const maturity=calculateDataMaturity(state,period,{summary:{questionsTotal:summary.questions,studyDays:summary.activeDays,sessions:summary.sessions,mockExams:summary.mockExams},disciplines}); return {version:"20260714-central-visual-desempenho-v1",period,filters,summary,comparison,daily,questions:summarizeRows(filteredQuestionRows(state,period,filters)),disciplines,mockExams:mocks,plannedVsActual,insights:buildDeterministicPerformanceInsights(summary,comparison,maturity,disciplines,plannedVsActual),maturity,stateUnchanged:before===JSON.stringify(state)}; }

  function classifyOverallSituation(summary, evolution, disciplines, dataQuality) { if (dataQuality.insufficient) return { classification:"DADOS INSUFICIENTES", explanation:"Há poucos lançamentos no período para um diagnóstico confiável." }; const critical=disciplines.filter(d=>d.isCritical).length, strong=disciplines.filter(d=>d.isStrong).length; if (summary.questionsTotal>=20 && summary.accuracyPct>=70 && summary.cebraspeNet>0 && critical===0) return {classification:"FAVORÁVEL", explanation:"O período combina volume mínimo, acerto elevado e líquido Cebraspe positivo."}; if (critical>=3 || summary.cebraspeNet<0 || summary.accuracyPct<50) return {classification:"CRÍTICA", explanation:`Desempenho exige atenção: líquido ${summary.cebraspeNet}, ${summary.accuracyPct}% de acerto e ${critical} disciplina(s) crítica(s).`}; return {classification:"ATENÇÃO", explanation:`Há ${strong} disciplina(s) forte(s), mas ${critical} ponto(s) crítico(s) ou lacunas de regularidade.`}; }
  function generateStrategicRecommendations(analysis) { if(analysis.dataMaturity?.phase==="calibration") return { highPriority:["Equilibrar disciplinas ativas e ampliar a coleta mínima de questões."], maintenance:["Registrar três sessões de estudo e manter continuidade."], reduceExcess:[], prioritySubjects:analysis.neglectedSubjects.slice(0,5).map(s=>`${s.discipline} — ${s.subject}: ${s.reason}`), weeklyDistribution:"Distribua a semana entre disciplinas, assuntos sem estudo e metas pendentes.", reviewSuggestions:"Concluir metas pendentes e registrar estudos sem criar metas automáticas.", suggestedQuestions:"Realizar pelo menos 20 questões em duas disciplinas, se possível.", imbalanceAlerts:analysis.dataQuality.metricsUnavailable }; let high=analysis.criticalDisciplines.map(d=>`${d.discipline}: ${d.justification}`).slice(0,5); if(!high.length) high=(analysis.preliminarySignals||[]).slice(0,3).map(s=>s.message); const subjects=analysis.neglectedSubjects.slice(0,5).map(s=>`${s.discipline} — ${s.subject}: ${s.reason}`); return { highPriority: high, maintenance: analysis.strongDisciplines.slice(0,5).map(d=>`${d.discipline}: manter revisões e questões.`), reduceExcess: analysis.disciplines.filter(d=>d.hours>0 && d.accuracyPct>=75 && d.questions>=20).slice(0,3).map(d=>`${d.discipline}: desempenho estabilizado; evitar concentração excessiva.`), prioritySubjects: subjects, weeklyDistribution: high.length?"Reserve 50% a 60% da semana para críticas/negligenciadas, 25% para manutenção e 15% para revisão geral.":"Distribua a semana entre manutenção, revisão e cobertura de assuntos pendentes.", reviewSuggestions: subjects.length?"Revisar assuntos negligenciados antes de novas frentes.":"Manter revisões espaçadas.", suggestedQuestions: high.length?"Priorize 30 a 50 questões semanais nas disciplinas críticas, ajustando ao tempo disponível.":"Manter lote semanal de questões por disciplina ativa.", imbalanceAlerts: analysis.dataQuality.metricsUnavailable }; }
  function dataQuality(state, period, summary, disciplines=[]) { const s=normalizeState(state); const fp=filterDataByPeriod(s,period); const disciplinesSet = new Set([...s.subjects.map(x=>x.name), ...s.syllabusItems.map(x=>x.discipline)].filter(Boolean)); const launched = new Set([...fp.studies.map(x=>studyDiscipline(x,s)), ...fp.questionLogs.map(x=>x.discipline)].filter(Boolean)); const inconsistentQuestionTotals=[...s.studies,...s.questionLogs].filter(x=>num(x.total||x.questions)>0 && num(x.correct)+num(x.wrong)+num(x.blank)>0 && num(x.total||x.questions)!==num(x.correct)+num(x.wrong)+num(x.blank)).length; const mockExamsWithoutResult=s.simulados.filter(x=>num(x.net??x.score??x.result)===0 && !("net" in x) && !("score" in x) && !("result" in x)).length; const mockQuestionQuality=summary.questionSummary?.dataQuality||[]; return { disciplinesWithoutEntries:[...disciplinesSet].filter(d=>!launched.has(d)), studiesWithoutSubject:s.studies.filter(x=>!x.subjectId&&!x.discipline).length, studiesWithoutTopic:s.studies.filter(x=>!x.topic&&!x.subject&&!x.syllabusItemId).length, questionsWithoutDiscipline:s.questionLogs.filter(x=>!x.discipline).length, questionsWithoutSubject:s.questionLogs.filter(x=>!x.subject&&!x.topic&&!x.syllabusItemId).length, inconsistentQuestionTotals, mockExamsWithoutResult, disciplinesBelow20Questions:disciplines.filter(d=>d.questions>0&&d.questions<20).map(d=>`${d.discipline} (${d.questions})`), insufficient: summary.sessions<2 && summary.questionsTotal<10 && summary.mockExams===0, metricsUnavailable:mockQuestionQuality, mockQuestionQuality }; }
  function buildStrategicAnalysis(state, selection="30d", custom={}, options={}) { const before=JSON.stringify(state); const period=getAnalyticsPeriod(selection,custom,options), previous=previousPeriod(period); const study=calculateStudySummary(state,period), questions=calculateQuestionSummary(state,period), goals=calculateGoalStats(state,period), mockExams=calculateMockExamStats(state,period); const summary={...study, questionSummary:questions, questionsBySource:questions.bySource, questionsTotal:questions.total, correct:questions.correct, wrong:questions.wrong, blank:questions.blank, accuracyPct:questions.accuracyPct, cebraspeNet:questions.cebraspeNet, goalsPlanned:goals.planned, goalsCompleted:goals.completed, goalCompletionPct:goals.completionPct, mockExams:mockExams.count}; const disciplines=calculateDisciplinePerformance(state,period,previous,options); const dq=dataQuality(state,period,summary,disciplines); const analysis={ period, previousPeriod:previous, overallSituation:null, summary, evolution:compareAnalyticsPeriods(state,period), disciplines, strongDisciplines:disciplines.filter(d=>d.isStrong), criticalDisciplines:disciplines.filter(d=>d.isCritical), neglectedSubjects:calculateSubjectNeglect(state,period,options), efficiency:calculateStudyEfficiency(state,period), cebraspe:calculateCebraspeStats(state,period), mockExams, recommendations:null, dataQuality:dq, dataMaturity:null, baseline:null, preliminarySignals:[] }; analysis.overallSituation=classifyOverallSituation(summary,analysis.evolution,disciplines,dq); analysis.dataMaturity=calculateDataMaturity(state,period,analysis); analysis.baseline=analysis.dataMaturity.baseline; applyConfidenceToAnalysis(analysis); analysis.recommendations=generateStrategicRecommendations(analysis); analysis.stateUnchanged = before === JSON.stringify(state); return analysis; }
  return { getAnalyticsPeriod, resolveDashboardPeriod, buildPerformanceDashboard, buildDailyPerformanceSeries, buildDisciplinePerformanceSeries, buildMockExamEvolutionSeries, buildPlannedVsActualSeries, comparePerformancePeriods, buildDeterministicPerformanceInsights, calculateDataMaturity, calculateDisciplineSampleConfidence, calculateBaseline, calculateNextDataMilestones, applyConfidenceToAnalysis, filterDataByPeriod, calculateStudySummary, normalizeMockExamQuestionRows, isDuplicateQuestionSource, calculateQuestionSummary, calculateCebraspeStats, calculateGoalStats, calculateDisciplinePerformance, calculateSubjectNeglect, calculateStudyEfficiency, calculateMockExamStats, compareAnalyticsPeriods, classifyOverallSituation, generateStrategicRecommendations, buildStrategicAnalysis };
});
