(function(root,factory){ if(typeof module==='object'&&module.exports) module.exports=factory(); else root.StudyAdvisor=factory(); })(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const fmtH=h=>{const m=Math.round(Number(h||0)*60),hh=Math.floor(m/60),mm=m%60;return hh&&mm?`${hh}h${String(mm).padStart(2,'0')}`:hh?`${hh}h`:`${mm}min`;};
const ptxt=p=>p?`${p.days||''} dias (${p.start} a ${p.end})`:'período analisado';
function normalizeAdvisorQuestion(q){return norm(q).replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();}
function detectAdvisorIntent(q){const n=normalizeAdvisorQuestion(q); if(/(semana|fazer|plano|priori[dz]ar|prioridade)/.test(n))return'weekly_plan'; if(/(cebraspe|cespe|liquido|saldo)/.test(n))return'cebraspe'; if(/(quest(ao|oes)|fiz|realizei)/.test(n))return'questions'; if(/(hora|estudei|tempo)/.test(n))return'hours'; if(/(pior|critica|tirando pontos|fraca|ruim)/.test(n))return'critical_discipline'; if(/(forte|melhor|boa)/.test(n))return'strong_discipline'; if(/(neglig|revis|assunto|dias sem)/.test(n))return'neglected'; if(/(evolu|melhor que|periodo anterior|queda|aumento)/.test(n))return'evolution'; if(/(simulado)/.test(n))return'mocks'; if(/(meta)/.test(n))return'goals'; if(/(eficien)/.test(n))return'efficiency'; if(/(qualidade|suficient|confiav)/.test(n))return'data_quality'; if(/(acerto|erro|branco|desempenho de|quanto estudei|materia|disciplina)/.test(n))return'discipline_performance'; if(/(como estou|situacao|desempenho|resumo|geral)/.test(n))return'overall'; return'unsupported';}
function namesFromAnalysis(analysis){return (analysis?.disciplines||[]).map(d=>d.discipline).filter(Boolean);}
function matchName(question,names){const q=normalizeAdvisorQuestion(question); const matches=names.filter(n=>{const nn=normalizeAdvisorQuestion(n); return q.includes(nn)||nn.split(/\s+/).some(w=>w.length>3&&q.includes(w))||nn.includes(q);}); const uniq=[...new Set(matches)]; const exact=uniq.find(n=>q.includes(normalizeAdvisorQuestion(n))); return exact?{name:exact,ambiguous:false,matches:[exact]}:uniq.length===1?{name:uniq[0],ambiguous:false,matches:uniq}:uniq.length>1?{ambiguous:true,matches:uniq}:{name:null,ambiguous:false,matches:[]};}
function extractDisciplineFromQuestion(question,analysis,state){const names=[...namesFromAnalysis(analysis),...(state?.subjects||[]).map(s=>s.name),...(state?.syllabusItems||[]).map(i=>i.discipline)].filter(Boolean);return matchName(question,names);}
function extractSubjectFromQuestion(question,analysis,state){const names=(state?.syllabusItems||[]).map(i=>i.subject||i.topic).filter(Boolean);return matchName(question,names);}
function base(intent,title,answer,evidence=[],suggestions=[],ok=true){return{intent,title,answer,evidence,suggestions:suggestions.slice(0,3),confidence:ok?'alta':'baixa',dataSufficient:ok};}
function insufficient(intent,period){return base(intent,'Dados insuficientes',`No período de ${ptxt(period)}, não há dados suficientes para responder com segurança. Fato: a análise local encontrou poucos registros. Recomendação: registre estudos, questões, simulados ou metas antes de concluir tendências.`,[`Período: ${ptxt(period)}`],['Como está meu desempenho?'],false);}
function answerOverallSituation({analysis,period}){if(!analysis||analysis.dataQuality?.insufficient)return insufficient('overall',period);const s=analysis.summary,c=analysis.overallSituation;const pri=(analysis.criticalDisciplines||[]).slice(0,2).map(d=>d.discipline).join(' e ')||'nenhuma disciplina crítica';return base('overall','Situação geral',`Nos últimos ${ptxt(period)}, sua situação foi classificada como ${c.classification}. Fatos: você estudou ${fmtH(s.hours)}, realizou ${s.questionsTotal} questões, teve ${s.accuracyPct}% de acerto e líquido Cebraspe ${s.cebraspeNet}. Motivo: ${c.explanation} Recomendação: priorize ${pri}.`,[`Horas: ${fmtH(s.hours)}`,`${s.questionsTotal} questões`,`${s.accuracyPct}% de acerto`,`líquido ${s.cebraspeNet}`],['Qual disciplina devo priorizar?','Estou melhor que no período anterior?','O que devo fazer nesta semana?']);}
function answerStudyHours({analysis,period}){const s=analysis?.summary;if(!s||!s.sessions)return insufficient('hours',period);return base('hours','Horas estudadas',`No período de ${ptxt(period)}, você estudou ${fmtH(s.hours)} em ${s.sessions} sessão(ões). Fato obtido dos registros de estudo e metas com tempo realizado. Motivo: a média diária foi ${s.dailyAverageHours}h.`,[`Horas: ${fmtH(s.hours)}`,`Sessões: ${s.sessions}`,`Dias com estudo: ${s.studyDays}`],['Quantas questões fiz?','Como está meu desempenho?']);}
function answerQuestionStats({analysis,period}){const s=analysis?.summary;if(!s||!s.questionsTotal)return insufficient('questions',period);return base('questions','Questões e acertos',`No período de ${ptxt(period)}, você fez ${s.questionsTotal} questões: ${s.correct} acertos, ${s.wrong} erros e ${s.blank} brancos. O percentual de acerto foi ${s.accuracyPct}% e o líquido Cebraspe foi ${s.cebraspeNet}.`,[`${s.questionsTotal} questões`,`${s.correct} acertos`,`${s.wrong} erros`,`${s.blank} brancos`,`${s.accuracyPct}% de acerto`,`líquido ${s.cebraspeNet}`],['Como está meu desempenho Cebraspe?','Qual disciplina mais está tirando pontos?']);}
function answerDisciplinePerformance(ctx){const m=extractDisciplineFromQuestion(ctx.question,ctx.analysis,ctx.state);if(m.ambiguous)return base('discipline_performance','Disciplina ambígua',`Você mencionou uma disciplina de forma ambígua. Selecione: ${m.matches.join(', ')}.`,m.matches,[],false);const d=(ctx.analysis?.disciplines||[]).find(x=>x.discipline===m.name);if(!d)return insufficient('discipline_performance',ctx.period);return base('discipline_performance',d.discipline,`No período de ${ptxt(ctx.period)}, ${d.discipline} recebeu ${fmtH(d.hours)}, com ${d.questions} questões, ${d.accuracyPct}% de acerto e líquido ${d.net}. Fato: dados agregados por disciplina. Motivo: ${d.justification}`, [`${fmtH(d.hours)} estudadas`,`${d.questions} questões`,`${d.accuracyPct}% de acerto`,`líquido ${d.net}`],[`Como evoluiu ${d.discipline}?`,`Quais assuntos precisam de revisão?`]);}
function answerCriticalDiscipline(ctx){const d=ctx.analysis?.criticalDisciplines?.[0];if(!d)return insufficient('critical_discipline',ctx.period);return base('critical_discipline','Disciplina crítica',`${d.discipline} apresenta o quadro mais crítico no período de ${ptxt(ctx.period)}: ${d.accuracyPct}% de acerto, líquido ${d.net} e ${d.evolution===null?'sem base anterior':`evolução de ${d.evolution} p.p.`}. Motivo: ${d.justification}`, [`Disciplina: ${d.discipline}`,`${d.questions} questões`,`${d.accuracyPct}%`,`líquido ${d.net}`],[`Quanto estudei ${d.discipline}?`,`O que devo fazer nesta semana?`]);}
function answerStrongDiscipline(ctx){const d=ctx.analysis?.strongDisciplines?.[0];if(!d)return insufficient('strong_discipline',ctx.period);return base('strong_discipline','Disciplina forte',`${d.discipline} foi a disciplina mais forte no período de ${ptxt(ctx.period)}: ${d.accuracyPct}% de acerto, líquido ${d.net} e ${fmtH(d.hours)} estudadas.`,[`${d.questions} questões`,`${d.accuracyPct}%`,`líquido ${d.net}`],['Onde estou estudando demais?']);}
function answerNeglectedSubjects(ctx){const rows=ctx.analysis?.neglectedSubjects||[];if(!rows.length)return insufficient('neglected',ctx.period);return base('neglected','Assuntos negligenciados',`No período de ${ptxt(ctx.period)}, os principais assuntos negligenciados são: ${rows.slice(0,5).map(s=>`${s.discipline} — ${s.subject} (${s.reason})`).join('; ')}. Fato: itens pendentes sem estudo recente, sem questões ou com metas pendentes.`,rows.slice(0,5).map(s=>`${s.discipline} — ${s.subject}: ${s.reason}`),['Quais assuntos precisam de revisão?','O que devo fazer nesta semana?']);}
function answerEvolution(ctx){const e=ctx.analysis?.evolution;if(!e)return insufficient('evolution',ctx.period);return base('evolution','Evolução',`Comparando ${ptxt(ctx.period)} com o período anterior, horas tiveram ${e.hours.direction} (${e.hours.delta}), questões tiveram ${e.questions.direction} (${e.questions.delta}), acerto teve ${e.accuracyPct.direction} (${e.accuracyPct.delta} p.p.) e líquido Cebraspe teve ${e.cebraspeNet.direction} (${e.cebraspeNet.delta}).`,[`Comparação com período anterior`, `Acerto: ${e.accuracyPct.delta}`,`Líquido: ${e.cebraspeNet.delta}`],['Como está meu desempenho?']);}
function answerCebraspe(ctx){const c=ctx.analysis?.cebraspe;if(!c)return insufficient('cebraspe',ctx.period);return base('cebraspe','Desempenho Cebraspe',`No período de ${ptxt(ctx.period)}, seu líquido Cebraspe foi ${c.net}. Fato: acertos menos erros, com brancos neutros. Principais somadores: ${(c.topAdders||[]).map(d=>d.discipline).join(', ')||'nenhum'}. Principais redutores: ${(c.topSubtractors||[]).map(d=>d.discipline).join(', ')||'nenhum'}.`,[`Líquido: ${c.net}`],['Qual disciplina mais está tirando pontos?']);}
function answerMockExams(ctx){const m=ctx.analysis?.mockExams;if(!m||!m.count)return insufficient('mocks',ctx.period);return base('mocks','Simulados',`No período de ${ptxt(ctx.period)}, foram ${m.count} simulado(s), média líquida ${m.averageNet}, melhor ${m.bestNet}, pior ${m.worstNet} e tendência de ${m.trend}.`,[`Simulados: ${m.count}`,`Média: ${m.averageNet}`],['Estou melhor que no período anterior?']);}
function answerGoals(ctx){const s=ctx.analysis?.summary;if(!s||!s.goalsPlanned)return insufficient('goals',ctx.period);return base('goals','Metas',`No período de ${ptxt(ctx.period)}, havia ${s.goalsPlanned} meta(s) previstas e ${s.goalsCompleted} concluída(s), com cumprimento de ${s.goalCompletionPct}%.`,[`Metas previstas: ${s.goalsPlanned}`,`Concluídas: ${s.goalsCompleted}`],['O que devo fazer nesta semana?']);}
function answerEfficiency(ctx){const e=ctx.analysis?.efficiency;if(!e)return insufficient('efficiency',ctx.period);return base('efficiency','Eficiência',`No período de ${ptxt(ctx.period)}, a eficiência foi: ${e.questionsPerHour??'sem dados'} questões/hora, ${e.correctPerHour??'sem dados'} acertos/hora e líquido/hora ${e.netPerHour??'sem dados'}. Aviso: ${e.warning}`,Object.entries(e).map(([k,v])=>`${k}: ${v}`),['Onde estou estudando demais?']);}
function answerWeeklyPlan(ctx){const r=ctx.analysis?.recommendations;if(!r)return insufficient('weekly_plan',ctx.period);return base('weekly_plan','Plano semanal',`PRIORIDADE ALTA\n${(r.highPriority||[]).map(x=>'- '+x).join('\n')||'- Sem prioridade crítica identificada.'}\n\nMANUTENÇÃO\n${(r.maintenance||[]).map(x=>'- '+x).join('\n')||'- Manter distribuição equilibrada.'}\n\nREVISÕES\n- ${r.reviewSuggestions}\n\nALERTA\n${(r.prioritySubjects||[]).map(x=>'- '+x).join('\n')||'- Sem alerta específico.'}\n\nFato: plano baseado nas recomendações do analytics-engine para ${ptxt(ctx.period)}. Recomendação: revise antes de aplicar; nenhuma meta é alterada automaticamente.`,[...(r.highPriority||[]),...(r.prioritySubjects||[]),r.weeklyDistribution,r.suggestedQuestions].filter(Boolean),['Quais assuntos precisam de revisão?','Qual disciplina devo priorizar?']);}
function answerDataQuality(ctx){const d=ctx.analysis?.dataQuality;if(!d)return insufficient('data_quality',ctx.period);return base('data_quality','Qualidade dos dados',`No período de ${ptxt(ctx.period)}, dados insuficientes: ${d.insufficient?'sim':'não'}. Estudos sem vínculo: ${d.studiesWithoutSubject}. Questões sem disciplina: ${d.questionsWithoutDiscipline}. Isso limita conclusões quando há poucos registros.`,[`Insuficiente: ${d.insufficient}`,`Estudos sem vínculo: ${d.studiesWithoutSubject}`,`Questões sem disciplina: ${d.questionsWithoutDiscipline}`],['Como está meu desempenho?'],!d.insufficient);}
function buildAdvisorAnswer(ctx){const intent=detectAdvisorIntent(ctx.question);const map={overall:answerOverallSituation,hours:answerStudyHours,questions:answerQuestionStats,discipline_performance:answerDisciplinePerformance,critical_discipline:answerCriticalDiscipline,strong_discipline:answerStrongDiscipline,neglected:answerNeglectedSubjects,evolution:answerEvolution,cebraspe:answerCebraspe,mocks:answerMockExams,goals:answerGoals,efficiency:answerEfficiency,weekly_plan:answerWeeklyPlan,data_quality:answerDataQuality}; if(!map[intent])return base('unsupported','Pergunta não suportada','Consigo analisar apenas seus dados de estudo, questões, metas, simulados, revisões e evolução. Tente perguntar qual disciplina priorizar ou como foi seu desempenho nos últimos 30 dias.',[],['Como está meu desempenho?','Qual disciplina devo priorizar?','O que devo fazer nesta semana?'],false);return map[intent](ctx);} 
return {normalizeAdvisorQuestion,detectAdvisorIntent,extractDisciplineFromQuestion,extractSubjectFromQuestion,answerOverallSituation,answerStudyHours,answerQuestionStats,answerDisciplinePerformance,answerCriticalDiscipline,answerStrongDiscipline,answerNeglectedSubjects,answerEvolution,answerCebraspe,answerMockExams,answerGoals,answerEfficiency,answerWeeklyPlan,answerDataQuality,buildAdvisorAnswer};
});
