const assert = require('node:assert/strict');
const fs = require('node:fs');
const test = require('node:test');
const nav = require('../advisor-navigation-engine.js');
const analytics = require('../analytics-engine.js');
function state(){return {subjects:[{id:'p',name:'Processo Penal'}],studies:[{date:'2026-07-10',discipline:'Processo Penal',minutes:240,correct:30,wrong:20,blank:0}],questionLogs:[{date:'2026-07-11',discipline:'Processo Penal',subject:'Ação penal',total:50,correct:35,wrong:15,blank:0,board:'Cebraspe'}],dailyGoals:[{date:'2026-07-12',discipline:'Processo Penal',status:'Pendente'}],syllabusItems:[{id:'1',discipline:'Processo Penal',subject:'Ação penal',status:'Concluído'},{id:'2',discipline:'Processo Penal',subject:'Prisões',status:'Pendente'}],smartReviews:[{date:'2026-07-13',discipline:'Processo Penal',status:'Pendente'}],simulados:[{date:'2026-07-12',net:55,goal:70}]};}
const fullMission={contestName:'TJ',positionName:'Analista',examDate:'2026-09-14',targetNetScore:80,targetAccuracyPct:75,targetSyllabusCoveragePct:100,targetReviewsPct:80,targetMockExams:4,weeklyAvailableMinutes:900};
function guidance(m=fullMission,s=state()){const a=analytics.buildStrategicAnalysis(s,'30d',{}, {today:'2026-07-14'}); return nav.buildAutonomousGuidance({state:s,analysis:a,mission:m,navigation:{autonomyMode:'copilot'},options:{today:'2026-07-14'}});}
test('destino parcial e completo',()=>{assert.equal(nav.validateAdvisorMission({contestName:'TJ'}).partial,true); assert.equal(nav.validateAdvisorMission(fullMission,{today:'2026-07-14'}).partial,false);});
test('ritmo atual e necessário',()=>{const g=guidance(); assert.ok(g.currentPace.studyMinutesPerWeek>0); assert.ok(g.requiredPace.weeksUntilExam>0);});
test('criação e escolha das rotas',()=>{const g=guidance(); assert.equal(g.routes.length,7); assert.ok(['equilibrada','cobertura','desempenho','recuperação','revisão','reta final','manutenção'].includes(g.bestRoute.type));});
test('inviabilidade e confiança',()=>{const g=guidance({...fullMission,examDate:'2026-07-15',targetNetScore:200,targetAccuracyPct:99,weeklyAvailableMinutes:30}); assert.match(g.feasibility.label,/baixa|inviável/); assert.ok(g.bestRoute.confidence>=20);});
test('próximo passo e recálculo',()=>{const g=guidance(); assert.match(g.nextBestAction.action,/registre|revisão|edital|simulado|meta/i); const n=nav.recalculateActiveRoute({routeHistory:[]},{state:state(),analysis:analytics.buildStrategicAnalysis(state(),'30d',{}, {today:'2026-07-14'}),mission:fullMission,options:{today:'2026-07-14'}}); assert.equal(n.routeHistory.length,1);});
test('modos de autonomia preservados',()=>{const g=guidance(fullMission); assert.equal(g.autonomyMode,'copilot'); const g2=nav.buildAutonomousGuidance({...g,state:state(),analysis:analytics.buildStrategicAnalysis(state(),'30d',{}, {today:'2026-07-14'}),mission:fullMission,navigation:{autonomyMode:'autopilot'},options:{today:'2026-07-14'}}); assert.equal(g2.autonomyMode,'autopilot');});
test('preservação de dados',()=>{const s=state(), before=JSON.stringify(s); guidance(fullMission,s); assert.equal(JSON.stringify(s),before);});
test('sincronização e backup antigo compatíveis',()=>{const src=fs.readFileSync('script.js','utf8'); assert.match(src,/advisorMission/); assert.match(src,/replaceState\(nextState\)/); assert.doesNotMatch(src,/mergeArrays\(state\.advisorMission/);});
test('ausência de comunicação externa no motor',()=>{const src=fs.readFileSync('advisor-navigation-engine.js','utf8'); assert.equal(/fetch|XMLHttpRequest|WebSocket|EventSource|navigator\.sendBeacon|OpenAI|Gemini|Claude|eval\(|new Function|https?:\/\//i.test(src),false);});
test('paridade raiz/docs e mobile sem overflow',()=>{for(const f of ['advisor-navigation-engine.js','script.js','style.css','index.html']) assert.equal(fs.readFileSync(f,'utf8'),fs.readFileSync('docs/'+f,'utf8')); const css=fs.readFileSync('style.css','utf8'); assert.match(css,/max-width: 100%/); assert.match(css,/max-width: 430px/);});
