const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const engine = require('../analytics-engine.js');
const advisor = require('../study-advisor.js');
const baseState = () => ({subjects:[{id:'t',name:'Direito Tributário'},{id:'c',name:'Direito Civil'}],studies:[],questionLogs:[],dailyGoals:[],syllabusItems:[{id:'s1',discipline:'Direito Civil',subject:'Contratos',status:'Pendente'}],smartReviews:[],simulados:[]});
const qlog=(discipline,total,correct,date='2026-07-10')=>({date,discipline,subject:'Geral',total,correct,wrong:total-correct,blank:0,board:'Cebraspe'});
function analysis(s){return engine.buildStrategicAnalysis(s,'30d',{}, {today:'2026-07-13'});} 
test('base vazia e poucos dados retornam calibração/confiança baixa',()=>{const a=analysis({});assert.equal(a.dataMaturity.phase,'calibration');assert.equal(a.dataMaturity.level,'low');assert.ok(a.dataMaturity.score>=0&&a.dataMaturity.score<=100);});
test('score cresce com novos registros e é limitado a 100',()=>{const low=analysis({...baseState(),questionLogs:[qlog('Direito Tributário',5,3)]});const high=analysis({...baseState(),studies:Array.from({length:12},(_,i)=>({date:`2026-07-${String(i+1).padStart(2,'0')}`,discipline:'Direito Tributário',topic:'Geral',minutes:30})),questionLogs:[qlog('Direito Tributário',250,200),qlog('Direito Civil',60,45)],simulados:[{date:'2026-07-11',net:10},{date:'2026-07-12',net:12}]});assert.ok(high.dataMaturity.score>low.dataMaturity.score);assert.ok(high.dataMaturity.score<=100);});
test('linha de base usa registro mais antigo',()=>{const a=analysis({...baseState(),dailyGoals:[{date:'2026-07-03',discipline:'X'}],questionLogs:[qlog('Direito Tributário',10,5,'2026-07-08')],studies:[{date:'2026-07-05',discipline:'X',minutes:20}]});assert.equal(a.baseline.firstRecordDate,'2026-07-03');});
test('confiança individual por disciplina controla classificações e sinais',()=>{const a=analysis({...baseState(),questionLogs:[qlog('Direito Tributário',12,3),qlog('Direito Civil',25,10),qlog('Processo Penal',55,50)]});const trib=a.disciplines.find(d=>d.discipline==='Direito Tributário');const civ=a.disciplines.find(d=>d.discipline==='Direito Civil');const proc=a.disciplines.find(d=>d.discipline==='Processo Penal');assert.equal(trib.classificationStatus,'insufficient');assert.equal(civ.sampleConfidence,'medium');assert.equal(proc.sampleConfidence,'high');assert.ok(!a.strongDisciplines.some(d=>d.discipline==='Direito Tributário'));assert.ok(!a.criticalDisciplines.some(d=>d.discipline==='Direito Tributário'));assert.ok(a.preliminarySignals.some(s=>s.discipline==='Direito Tributário'));});
test('situação geral e evolução não inventam conclusão durante calibração',()=>{const a=analysis({...baseState(),questionLogs:[qlog('Direito Tributário',8,2)]});assert.notEqual(a.overallSituation.classification,'CRÍTICA');assert.match(a.evolution.questions.direction,/dados insuficientes|ausência/);});
test('conselheiro informa confiança, pior disciplina sem amostra e próximo marco',()=>{const s={...baseState(),questionLogs:[qlog('Direito Tributário',8,3)]};const a=analysis(s);let r=advisor.buildAdvisorAnswer({question:'Qual matéria está pior?',analysis:a,state:s,period:a.period});assert.match(r.answer,/Confiança baixa/);assert.match(r.answer,/Ainda não existe amostra suficiente/);assert.match(r.answer,/Próximo marco/);r=advisor.buildAdvisorAnswer({question:'Como está meu desempenho?',analysis:a,state:s,period:a.period});assert.match(r.answer,/fase atual|Confiança baixa/);});
test('assuntos sem estudo são ausência de registro, plano não gera metas, state intacto',()=>{const s=baseState();const before=JSON.stringify(s);const a=analysis(s);assert.match(a.neglectedSubjects[0].reason,/Fato: Não há estudo registrado/);const r=advisor.buildAdvisorAnswer({question:'O que devo fazer nesta semana?',analysis:a,state:s,period:a.period});assert.match(r.answer,/nenhuma meta é alterada automaticamente/);assert.equal(JSON.stringify(s),before);assert.equal(a.stateUnchanged,true);});
test('sem comunicação externa nos módulos de calibração e paridade docs',()=>{for(const f of ['analytics-engine.js','study-advisor.js']){const src=fs.readFileSync(f,'utf8');assert.equal(/fetch\(|XMLHttpRequest|navigator\.sendBeacon|WebSocket|OpenAI|https?:\/\//.test(src),false);assert.equal(src,fs.readFileSync('docs/'+f,'utf8'));}});
test('botões de coleta e CSS mobile existem',()=>{const script=fs.readFileSync('script.js','utf8');const css=fs.readFileSync('style.css','utf8');assert.match(script,/data-view-link="dashboard"/);assert.match(script,/data-view-link="questoes"/);assert.match(script,/data-view-link="simulados"/);assert.match(css,/@media \(max-width: 720px\)/);assert.doesNotMatch(css,/overflow-x:\s*scroll/);});
