const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const advisor = require('../study-advisor.js');
const engine = require('../analytics-engine.js');
function state(){return {subjects:[{id:'p',name:'Processo Penal'},{id:'t',name:'Direito Tributário'},{id:'c',name:'Direito Civil'}],studies:[{date:'2026-07-10',discipline:'Processo Penal',minutes:510,correct:180,wrong:40,blank:10,board:'Cebraspe'},{date:'2026-07-09',discipline:'Direito Tributário',minutes:60,correct:24,wrong:26,blank:0,board:'Cebraspe'},{date:'2026-07-08',discipline:'Direito Civil',minutes:120,correct:30,wrong:30,blank:0,board:'Cebraspe'}],questionLogs:[{date:'2026-07-10',discipline:'Processo Penal',subject:'Ação penal',board:'Cebraspe',total:230,correct:190,wrong:40,blank:0}],dailyGoals:[{date:'2026-07-10',discipline:'Direito Tributário',status:'Pendente'},{date:'2026-07-11',discipline:'Direito Tributário',status:'Pendente'}],syllabusItems:[{id:'ml',discipline:'Medicina Legal',subject:'Traumatologia',status:'Pendente'}],simulados:[{date:'2026-07-10',net:70,goal:80},{date:'2026-07-12',net:90,goal:80}]};}
const analysis=()=>engine.buildStrategicAnalysis(state(),'30d',{}, {today:'2026-07-13'});
test('detecta intenções principais',()=>{assert.equal(advisor.detectAdvisorIntent('Como estou?'),'overall');assert.equal(advisor.detectAdvisorIntent('Quantas horas estudei?'),'hours');assert.equal(advisor.detectAdvisorIntent('Quantas questões fiz?'),'questions');assert.equal(advisor.detectAdvisorIntent('líquido Cebraspe'),'cebraspe');assert.equal(advisor.detectAdvisorIntent('Qual matéria está pior?'),'critical_discipline');});
test('detecta disciplina específica, ignora acentos e aceita parcial',()=>{const a=analysis();assert.equal(advisor.extractDisciplineFromQuestion('Quanto estudei processo penal?',a,state()).name,'Processo Penal');assert.equal(advisor.extractDisciplineFromQuestion('tributario',a,state()).name,'Direito Tributário');});
test('trata ambiguidade',()=>{const m=advisor.extractDisciplineFromQuestion('Direito',analysis(),state());assert.equal(m.ambiguous,true);});
test('responde dados insuficientes e não inventa',()=>{const a=engine.buildStrategicAnalysis({},'30d',{}, {today:'2026-07-13'});const r=advisor.buildAdvisorAnswer({question:'Quanto estudei Medicina?',analysis:a,state:{},period:a.period});assert.equal(r.dataSufficient,false);assert.match(r.answer,/não há dados suficientes|Consigo analisar/);});
test('responde plano semanal usando recomendações do analytics-engine',()=>{const a=analysis();const r=advisor.buildAdvisorAnswer({question:'O que devo fazer nesta semana?',analysis:a,state:state(),period:a.period});assert.equal(r.intent,'weekly_plan');assert.ok(r.evidence.some(e=>String(e).includes(a.recommendations.weeklyDistribution)));});
test('respostas incluem período e evidências',()=>{const a=analysis();const r=advisor.buildAdvisorAnswer({question:'Como está meu desempenho?',analysis:a,state:state(),period:a.period});assert.match(r.answer,/30 dias/);assert.ok(r.evidence.length);});
test('nenhuma alteração do state',()=>{const s=state(), before=JSON.stringify(s), a=engine.buildStrategicAnalysis(s,'30d',{}, {today:'2026-07-13'});advisor.buildAdvisorAnswer({question:'Como estou?',analysis:a,state:s,period:a.period});assert.equal(JSON.stringify(s),before);});
test('nenhuma comunicação externa',()=>{const src=fs.readFileSync('study-advisor.js','utf8');assert.equal(/fetch|XMLHttpRequest|WebSocket|EventSource|navigator\.sendBeacon|api[_-]?key|https?:\/\//i.test(src),false);});
test('histórico não persistido e mobile sem overflow',()=>{const script=fs.readFileSync('script.js','utf8');const css=fs.readFileSync('style.css','utf8');assert.doesNotMatch(script,/advisorConversation.*localStorage|localStorage.*advisorConversation|indexedDB.*advisorConversation/);assert.match(css,/advisor-screen, \.advisor-screen \* \{ max-width: 100%; box-sizing: border-box; \}/);});
test('raiz e docs idênticos',()=>{for(const f of ['study-advisor.js','script.js','style.css','index.html','service-worker.js']) assert.equal(fs.readFileSync(f,'utf8'),fs.readFileSync('docs/'+f,'utf8'));});
