"""Central DOCX emoji font normalizer.

Use this shared module for every DOCX generated by the system before saving or
uploading it. It preserves existing run formatting and only moves emoji
characters/sequences into dedicated runs using Segoe UI Emoji in all Word font
slots (ascii, hAnsi, eastAsia and cs).
"""
from __future__ import annotations

import copy
import re
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
NS = {"w": W_NS}
ET.register_namespace("w", W_NS)

EMOJI_FONT = "Segoe UI Emoji"
DOCX_XML_PART_RE = re.compile(r"^word/(?:document|header\d+|footer\d+|footnotes|endnotes|comments)\.xml$")

# Broad Unicode emoji coverage: pictographs, symbols, dingbats, regional flags,
# tag flags, enclosed/keycap sequences and characters commonly emoji-presented
# with U+FE0F. This intentionally avoids a fixed application-specific list.
EMOJI_SEQUENCE_RE = re.compile(
    "(?:"
    r"[0-9#*]\ufe0f?\u20e3"
    r"|[\U0001F1E6-\U0001F1FF]{2}"
    r"|[\U0001F3F4](?:[\U000E0061-\U000E007A]+\U000E007F)?"
    r"|[\U0001F000-\U0001FAFF][\ufe0f]?(?:\u200d[\U0001F000-\U0001FAFF][\ufe0f]?)*"
    r"|[\u2600-\u27BF]\ufe0f?"
    ")",
    re.UNICODE,
)


def split_emoji_text(text: str) -> list[tuple[str, bool]]:
    """Split text into (segment, is_emoji) preserving order and content."""
    parts: list[tuple[str, bool]] = []
    cursor = 0
    for match in EMOJI_SEQUENCE_RE.finditer(text or ""):
        if match.start() > cursor:
            parts.append((text[cursor:match.start()], False))
        parts.append((match.group(0), True))
        cursor = match.end()
    if cursor < len(text or ""):
        parts.append((text[cursor:], False))
    return parts


def _qn(local_name: str) -> str:
    return f"{{{W_NS}}}{local_name}"


def _ensure_emoji_rfonts(run: ET.Element) -> None:
    rpr = run.find("w:rPr", NS)
    if rpr is None:
        rpr = ET.Element(_qn("rPr"))
        run.insert(0, rpr)
    rfonts = rpr.find("w:rFonts", NS)
    if rfonts is None:
        rfonts = ET.Element(_qn("rFonts"))
        rpr.insert(0, rfonts)
    for attr in ("ascii", "hAnsi", "eastAsia", "cs"):
        rfonts.set(_qn(attr), EMOJI_FONT)


def normalize_paragraph_emoji_runs(paragraph: ET.Element) -> bool:
    """Split mixed text/emoji runs in a paragraph while preserving run style."""
    changed = False
    new_children = []
    for child in list(paragraph):
        if child.tag != _qn("r"):
            new_children.append(child)
            continue
        text_nodes = [node for node in child if node.tag == _qn("t")]
        if len(text_nodes) != 1:
            if any(EMOJI_SEQUENCE_RE.search(node.text or "") for node in text_nodes):
                _ensure_emoji_rfonts(child)
                changed = True
            new_children.append(child)
            continue
        text_node = text_nodes[0]
        segments = split_emoji_text(text_node.text or "")
        if len(segments) <= 1:
            if segments and segments[0][1]:
                _ensure_emoji_rfonts(child)
                changed = True
            new_children.append(child)
            continue
        for segment, is_emoji in segments:
            run = copy.deepcopy(child)
            run.find("w:t", NS).text = segment
            if is_emoji:
                _ensure_emoji_rfonts(run)
            new_children.append(run)
        changed = True
    if changed:
        paragraph[:] = new_children
    return changed


def normalize_docx_xml(xml_bytes: bytes) -> bytes:
    root = ET.fromstring(xml_bytes)
    changed = False
    for paragraph in root.findall(".//w:p", NS):
        changed = normalize_paragraph_emoji_runs(paragraph) or changed
    return ET.tostring(root, encoding="utf-8", xml_declaration=True) if changed else xml_bytes


def normalize_docx_emoji_fonts(source: str | Path, destination: str | Path | None = None) -> Path:
    """Normalize emoji fonts in every relevant XML part of a DOCX file."""
    source_path = Path(source)
    destination_path = Path(destination) if destination else source_path
    temp_path = destination_path.with_suffix(destination_path.suffix + ".tmp")
    with zipfile.ZipFile(source_path, "r") as zin, zipfile.ZipFile(temp_path, "w", zipfile.ZIP_DEFLATED) as zout:
        for info in zin.infolist():
            data = zin.read(info.filename)
            if DOCX_XML_PART_RE.match(info.filename):
                data = normalize_docx_xml(data)
            zout.writestr(info, data)
    temp_path.replace(destination_path)
    return destination_path


__all__ = [
    "EMOJI_FONT",
    "split_emoji_text",
    "normalize_paragraph_emoji_runs",
    "normalize_docx_xml",
    "normalize_docx_emoji_fonts",
]

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Normalize emoji runs in DOCX files.")
    parser.add_argument("docx", nargs="+", help="DOCX file(s) to normalize in place")
    args = parser.parse_args()
    for docx_path in args.docx:
        normalize_docx_emoji_fonts(docx_path)
